//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hangman", Namespace="http://schemas.datacontract.org/2004/07/GameService.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Array))]
    public partial class Hangman : object
    {
        
        private string HiddenWordField;
        
        private bool IsGameLostField;
        
        private bool IsGameWonField;
        
        private bool IsGuessCorrectField;
        
        private int LivesField;
        
        private System.Array UsedLettersField;
        
        private string VisibleWordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HiddenWord
        {
            get
            {
                return this.HiddenWordField;
            }
            set
            {
                this.HiddenWordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameLost
        {
            get
            {
                return this.IsGameLostField;
            }
            set
            {
                this.IsGameLostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameWon
        {
            get
            {
                return this.IsGameWonField;
            }
            set
            {
                this.IsGameWonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGuessCorrect
        {
            get
            {
                return this.IsGuessCorrectField;
            }
            set
            {
                this.IsGuessCorrectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lives
        {
            get
            {
                return this.LivesField;
            }
            set
            {
                this.LivesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Array UsedLetters
        {
            get
            {
                return this.UsedLettersField;
            }
            set
            {
                this.UsedLettersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisibleWord
        {
            get
            {
                return this.VisibleWordField;
            }
            set
            {
                this.VisibleWordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGameController")]
    public interface IGameController
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameController/CreateGame", ReplyAction="http://tempuri.org/IGameController/CreateGameResponse")]
        System.Threading.Tasks.Task<int> CreateGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameController/TerminateGame", ReplyAction="http://tempuri.org/IGameController/TerminateGameResponse")]
        System.Threading.Tasks.Task TerminateGameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameController/Guess", ReplyAction="http://tempuri.org/IGameController/GuessResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Hangman> GuessAsync(int id, string guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameController/NewGame", ReplyAction="http://tempuri.org/IGameController/NewGameResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Hangman> NewGameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameController/ComputeScore", ReplyAction="http://tempuri.org/IGameController/ComputeScoreResponse")]
        System.Threading.Tasks.Task<int> ComputeScoreAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IGameControllerChannel : ServiceReference1.IGameController, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GameControllerClient : System.ServiceModel.ClientBase<ServiceReference1.IGameController>, ServiceReference1.IGameController
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GameControllerClient() : 
                base(GameControllerClient.GetDefaultBinding(), GameControllerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGameController.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameControllerClient(EndpointConfiguration endpointConfiguration) : 
                base(GameControllerClient.GetBindingForEndpoint(endpointConfiguration), GameControllerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameControllerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GameControllerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameControllerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GameControllerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> CreateGameAsync()
        {
            return base.Channel.CreateGameAsync();
        }
        
        public System.Threading.Tasks.Task TerminateGameAsync(int id)
        {
            return base.Channel.TerminateGameAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Hangman> GuessAsync(int id, string guess)
        {
            return base.Channel.GuessAsync(id, guess);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Hangman> NewGameAsync(int id)
        {
            return base.Channel.NewGameAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ComputeScoreAsync(int id)
        {
            return base.Channel.ComputeScoreAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameController))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameController))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/GameService/GameController");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GameControllerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGameController);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GameControllerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGameController);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGameController,
        }
    }
}
